const data =  [
  {
      _id: '1',
      name: 'Nykaa Naturals Skin Potion Anti- Ageing Skincare Face Oil',
      category: 'skin-care',
      image:'/images/sk2.jpg',
      price: 499,
      countInStock: 10,
      brand: 'Lakme',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
  },
  {
      _id: '2',
      name: 'Nykaa Clay It Cool Daily Detox Clay Mask',
      category: 'clay',
      image: '/images/sk1.jpg',
      feature:'offer',
      price: 510,
      countInStock: 20,
      brand: 'Nykaa',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
  },
  {
      _id: '3',
      name: 'Nykaa Clay It Cool Pore Perfect Clay Mask',
      category: 'Facewash',
      image: '/images/sk3.jpg',
       feature:'BESTSELLER',
      price: 320,
      countInStock: 10,
      brand: 'Lotus',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
  },   
  {
    _id: '3',
    name: 'Nykaa Clay It Cool Pore Perfect Clay Mask',
    category: 'moisteriser',
    image: '/images/sk3.jpg',
     feature:'BESTSELLER',
    price: 320,
    countInStock: 10,
    brand: 'ponds',
    rating: 4.8,
    numReviews: 17,
    description: 'high quality product',
}, {
  _id: '3',
  name: 'Nykaa Clay It Cool Pore Perfect Clay Mask',
  category: 'Skincare',
  image: '/images/sk3.jpg',
   feature:'BESTSELLER',
  price: 320,
  countInStock: 10,
  brand: 'Nykaa',
  rating: 4.8,
  numReviews: 17,
  description: 'high quality product',
}, {
  _id: '3',
  name: 'Nykaa Clay It Cool Pore Perfect Clay Mask',
  category: 'Facewash',
  image: '/images/sk3.jpg',
   feature:'BESTSELLER',
  price: 320,
  countInStock: 10,
  brand: 'Himalayan',
  rating: 4.8,
  numReviews: 17,
  description: 'high quality product',
}, {
  _id: '3',
  name: 'Nykaa Clay It Cool Pore Perfect Clay Mask',
  category: 'talc',
  image: '/images/sk3.jpg',
   feature:'BESTSELLER',
  price: 320,
  countInStock: 10,
  brand: 'Lakme',
  rating: 4.8,
  numReviews: 17,
  description: 'high quality product',
},
 ]

  export default data;